### ISSUE TITLE
Rebuild Authentication to enable OAuth Access

### ISSUE THREAD

**Issue by DZunke** [DZunke/SlackBundle#12]
Tokens are deprecated. They are only for testing purposes.

https://api.slack.com/docs/oauth-test-tokens

It is needed to implement oauth2 as the prefered authentication. 

https://api.slack.com/docs/oauth

**Comment by elonmir** [comment]
Yeah, just stumbled upon that issue in our current project... I throw in a few beers if you fix it :D

**Comment by DZunke** [comment]
Sorry but there is no way to integrate oauth with background processes. The only way to retreive the needed data is with a standard web integration like "Login with Slack". The needed "code" will be delivered bay logging in to slack with redirect. 

Bot Integrations are not Working with PHP cause lacking of RTM-Features
Incoming Webhooks are only for Messaging Purposes

Extended Integrations without bigger integration in the web process are only available with the developement and testing tokens that are not really deprecated (as i said) but not the recommended way. I had a look at other slack integrations and they all use these tokens. 

The Current way with [Tokens for Testing](https://api.slack.com/docs/oauth-test-tokens) will stay.
