### ISSUE TITLE
Update composer.json to use guzzlehttp

### ISSUE THREAD

**Issue by vladab** [DZunke/SlackBundle#13]
There is a warning with guzzle composer dependency.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by DZunke** [comment]
Hey,

thanks for your hint. I will have a look at it in a few days along with some other changes to create a v2 tag. Hopefully i will be able to deliver it at the end of the next week, at latest!

**Comment by DZunke** [comment]
Sorry for delay. I have created a new branch 2.0-dev to create some Non-BC changes. The Guzzle upgrade to v6 is already included and should work if you want to try it :smile:

**Comment by alister** [comment]
I've got it working (at least, it sends a message via  `bin/console dzunke:slack:message`), however there were two issues:

1. I was being caught by my home ISPs proxy page before it would redirect to the secure URL, but adding `endpoint: "https://slack.com/api"` to the config sorted that (making it the default in `getConfigTreeBuilder()` may be useful).
2. In `Slack\Client\Response::parseGuzzleResponse()`:  Just  `$guzzleResponse->getBody(true)`, returns a `GuzzleHttp\Psr7\Stream`, so ....

    // To return the contents of the response, decoded
    $responseArray = json_decode($guzzleResponse->getBody()**->getContents()**, true);

     // Also usefully, PHP 5.6+ allows for:
    use function GuzzleHttp\json_decode;
     // Wrapper for json_decode that throws when an error occurs.

Thanks for all your efforts.

**Comment by alister** [comment]
I've made https://github.com/DZunke/SlackBundle/pull/16 with the two changes

**Comment by DZunke** [comment]
Thanks for the MR. I think all is working now. My [test.php](https://gist.github.com/DZunke/0e759304a074d103bc62bed1d7e9ea80) is working. Missed that i'd used https and haven't added it to the defaults. Sorry!

**Comment by alister** [comment]
"dev-2.0-dev" has been running in prod on my site for a while now - admittedly, with very light traffic - but there's been no issues for me with the bundle/code. If you wanted to make a 2.0.0 release, I'd happily update my own composer.json for it.

**Comment by DZunke** [comment]
Hey alister, sorry for late Response. Seems i have no time to run for some changes i had planed so i will prepare release 2.0 today. Thanks for your support 😺
