### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by RonanSauvage** [DZunke/SlackBundle#19]
Since the v2.0, in my localhost when SlackBundle wants to send one message, i've this error : 

cURL error 60: SSL certificate problem: unable to get local issuer certificate

So I think this is a problem since you remplace guzzle by httpguzzle ?

Maybe you can let us set few parameters when you create ur $guzzle. 

In fact, I think I need, in executeRequest method : 
`$client = new GuzzleHttp\Client(['defaults' => ['verify' => false]]);`

Can we set parameters ?

**Comment by DZunke** [comment]
Hi @RonanSauvage,

i think it should be no problem to put in client options into the connection configuration. The Connection inherits Stuff like Retries. To extend the class with the guzzle verify option seems good placed. At least the Class Client should be extended to give the GuzzleClient Initialization the option. 

Thats what i could say by the first look. 

I am off till tomorrow evening, so i will try to check it on sunday (calendar entry placed)

For security reasons the best way surely would be to fix the curl client problem. Are you able to send requests with curl on the console? If not ... this problem on your system should also be fixed but for quickfixing the problem the option seems legit 😉

**Comment by DZunke** [comment]
Hey @RonanSauvage ,

today i'd released v2.1.0 with the option to set Guzzles SSL Verification. As default it is set to true, so you have to give the connection the option "verifySsl". With the Basic Implementation you have to call ```$connection->setVerifySsl(false);``` but with the Symfony Bundle Configuration there is the new config ```verify_ssl: false```

Hope this works for you!

**Comment by RonanSauvage** [comment]
Hey @DZunke, 

This new feature is awesome. Thx a lot. 
New config functional in my project. Good to see lot of errors in my slack channel :) 

Thank you for your speed and reliability. 
rmA

**Comment by DZunke** [comment]
Thanks. Good to hear it works fine. So I'll close this Issue now 😸
