### ISSUE TITLE
Feature request: creating channel

### ISSUE THREAD

**Issue by sergionegri** [DZunke/SlackBundle#24]
Would it be complicated to add the possibility to create a channel?
This way from an external app you can create it and then start publishing into it.

**Comment by DZunke** [comment]
Hey @sergionegri,

no this would be no problem. We only have to implement a new Action for [channel.create](https://api.slack.com/methods/channels.create)

Do you have the possibility to do it by yourself or do you need support of me? 

Greets

**Comment by sergionegri** [comment]
I'd immensely appreciate if you could do it. It would take me a lot of trial error to replicate what you have done in other actions.

**Comment by DZunke** [comment]
Ok. As you wish. 😉

**Comment by DZunke** [comment]
I've released 2.3.0 with new channels.create action. Also i've extended the channels service for a shortcut to the method. Hope it works for you. A short feedback would be nice 😉

**Comment by sergionegri** [comment]
Hello. I had been using version 1.4 due to Symfony version constraint. Now, to use your 2.3 I've upgraded to 2.8, but I'm experiencing this error:
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by DZunke** [comment]
Ok. Otherwise there is the Issue #19 which has a workaround implemented 😸

**Comment by sergionegri** [comment]
It worked like a charm the creation of a new channel, thanks again, you've been very kind :)
Thanks also for directing me to the workaround ;)

**Comment by DZunke** [comment]
Ok! Thanks for your Feedback. I'll close the Issue. Have Fun!
