### ISSUE TITLE
Is icon_url attribute working?

### ISSUE THREAD

**Issue by sergionegri** [DZunke/SlackBundle#25]
I tried to add the icon_url attribute. I tried both with a file on my local machine and a file that is openly accessible. In both cases it's not showing.
I imagine, being an url, that that file must be accessible from outside (a public url).
Anyways, I've read in the documentation that it must be used in conjunction with "as_user = false" otherwise it gets ignored. But we cannot specify as_user = false as attribute when creating a message, right? Maybe because it was not accessible under https?

**Comment by DZunke** [comment]
Hi @sergionegri,

i'll have to do a small testi. I had it worked once, maybe there were some changes in the API. Sorry if there are problems with the setting! 

Greetings

**Comment by DZunke** [comment]
Sooo ... had you defined an icon_emoji? Cause it will not work with icon_url. 

I'd tested with the following identity:

```php
$identity = new \DZunke\SlackBundle\Slack\Messaging\Identity();
$identity->setUsername('CoffeeBrewer');
$identity->setIconUrl('http://image.flaticon.com/teams/1-freepik.jpg');
```

The moment i also set an emoji for the identity the emoji had been used

**Comment by DZunke** [comment]
have extended the docs to ensure the info is in there

**Comment by sergionegri** [comment]
It works, sorry. The issue was that while testing I was sending several messages very close to one another, and Slack does not repeat the icon (so it had already the default icon and did not show the new one). You can close the issue, thank you again for your time!

**Comment by DZunke** [comment]
No Problem. Its good to know if there were issues. Thanks!
