### ISSUE TITLE
Symfony 3.4 deprecations (registering commands)

### ISSUE THREAD

**Issue by alister** [DZunke/SlackBundle#28]
Auto-registration of the command "DZunke\SlackBundle\Command\BotMessagingCommand" is deprecated since Symfony 3.4

Also for:

* "DZunke\SlackBundle\Command\ChangeChannelsTopicCommand"
* "DZunke\SlackBundle\Command\DebugCommand"
* "DZunke\SlackBundle\Command\MessageCommand"
* "DZunke\SlackBundle\Command\UsersCommand"

Just being in the Command/ directory is no longer enough. They must also be tagged. This can be done explicitly, listing them in the ./Resources/config/services.yml file, or with Symfony 3.3+ they can also be tagged if they extend a particular class - `Symfony\Component\Console\Command\Command` is probably best.

**Comment by arthens** [comment]
@DZunke it doesn't look like this was ever released. Is there any plan to release version 2.4 (or 3) soon?

**Comment by DZunke** [comment]
Hey @arthens ,

thanks for the Question. There will be a 3.0 release. It is at the top 3 of my trello cards. so it moved forward the last months. I could do the 3.0 release before my planned small rebuilds for the core if you need a released version with the Current Changelog of Master. It has to be 3.0 cause of the bc break. After 3.0 it maybe it is a good idea to split the master a bit to support better bugfixing.

Ok ... i cannot promise to work on it in the next 3 weeks but if you need the release i could do that first in the near future.
