### ISSUE TITLE
Removing deprecated names and using 'slack:...' as names

### ISSUE THREAD

**Issue by alister** [DZunke/SlackBundle#30]
From 

    ->setName('dzunke:slack:message')
    ->setAliases(['slack:message'])

to

     ->setName('slack:message')

etc, in the commands `configure()` methods.  This closes the commit from db0247ccf1

**Comment by alister** [comment]
Setting the new name like:
````
protected static $defaultName = 'slack:message';

protected function configure() {
    $this->setName(static::$defaultName)
````
[allows for commands to be registered at compile time](https://github.com/symfony/console/blob/315748809dc4424c2e7a5dcdaee1ceb6aca34f02/CHANGELOG.md#340), used in the setName for backward compatibility.

**Comment by alister** [comment]
Turns out you also have to [tag the command-service](https://symfony.com/blog/new-in-symfony-3-4-lazy-commands) with  `command: slack:name...` as well to  lazy-build the services, but that can be done another time. Maybe an 'EasyFix' label on a Github issue?

**Comment by DZunke** [comment]
You're right. I've changed it in 2c760a63bf6c6ddb36b08600176e16928c93bca5
