### ISSUE TITLE
Question: Any plans for supporting Symfony 4.*?

### ISSUE THREAD

**Issue by Mahmoudz** [DZunke/SlackBundle#36]
Hi @DZunke, thanks for this useful package.

I'm in the process of upgrading a legacy codebase from Symfony 3.4 to 4.1. 
And I was wondering if you have plans for supporting Sy4 anytime soon "like within 48 hours"!?
It's ok if you don't have time for it now, I may get someone or myself to handle it and contribute back, if you don't mind.

Best,

**Comment by DZunke** [comment]
Hi @Mahmoudz,

all Symfony 4 versions are now supported with version 2.4.0. Support for Symfony flex is not planed cause i do not like it 😉 

Hope this helps! Will close this issue for now.

Greets
