### ISSUE TITLE
cannotBeEmpty() at path "d_zunke_slack.identities" has no effect

### ISSUE THREAD

**Issue by mitch10593** [DZunke/SlackBundle#38]
In Symfony 3.4, the cannotBeEmpty directive cause this message:

> Using Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::cannotBeEmpty() at path "d_zunke_slack.identities" has no effect, consider requiresAtLeastOneElement() instead. In 4.0 both methods will behave the same.

in DZunke/SlackBundle/DependencyInjection/Configuration.php:

```php
        /** @var $connectionNode ArrayNodeDefinition */
        $microservicesNode = $node->requiresAtLeastOneElement()
            ->useAttributeAsKey('username')
            ->cannotBeEmpty()
            ->info('Usernames to use for Communication inside the Messaging')
            ->prototype('array');
```

Removing cannotBeEmpty() solve the deprecated alert (and I think requiresAtLeastOneElement and useAttributeAsKey should not be used at the same time).

The working version:

```php
        /** @var $connectionNode ArrayNodeDefinition */
        $microservicesNode = $node->requiresAtLeastOneElement()
            ->useAttributeAsKey('username')
            ->info('Usernames to use for Communication inside the Messaging')
            ->prototype('array');
```

**Comment by DZunke** [comment]
This was resolves with #40 by @syunta 👍
